piVersion: apps/v1
kind: Deployment
metadata:
  name: gameover-mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: gameover-secret
              key: dbUser
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gameover-secret
              key: dbPassword
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gameover-secret
              key: dbRootPassword
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: gameover-mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql